[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datasetter"
version = "0.1.1"
dependencies = [
]

[project.scripts]
tuna = "datasetter.__main__:main"

[tool.setuptools.packages.find]
where = ["src"]
